ip: "127.0.0.1"
port: 8885
api:
  min_password_size: 1
  max_password_size: 32
  min_username_size: 1
  max_username_size: 32
jwt:
  secret: "secret123"
usecase:
  default_message: "hello, world"
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "sandbox"
